import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LuCircleGauge } from "react-icons/lu";
import { IoWalletOutline } from "react-icons/io5";
import { PiCoins } from "react-icons/pi";
import { CgArrowsExchange } from "react-icons/cg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex justify-center items-center`}
      >
        <div className="w-[80%] h-[80%] bg-gray-700 flex justify-center items-center ">
          <div className=" w-[97%] h-[96%] bg-gray-500 rounded-4xl">
            {/* navbar */}
            <div className="navbar">
              <nav className="bg-transparent border-gray-200 dark:bg-gray-900">
                <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
                  <a
                    href="https://flowbite.com/"
                    className="flex items-center space-x-3 rtl:space-x-reverse"
                  >
                    <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">
                      Dashboard
                    </span>
                  </a>
                  <div className="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
                    <button
                      type="button"
                      className="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"
                    >
                      Sign in
                    </button>
                    <button
                      type="button"
                      className="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
                    >
                      Sign Up
                    </button>
                  </div>
                </div>
              </nav>
            </div>

            {/* Body */}
            <div className=" flex ">
              {/* sidebar */}
              <div className=" w-[10%] ">
                <div className="bg-gray-600 w-[60%] mx-auto bg- h-[100%]">
                  <LuCircleGauge className="h-[2rem] w-[2rem]"  />
                  <IoWalletOutline className="h-[2rem] w-[2rem]"/>
                  <PiCoins className="h-[2rem] w-[2rem]"/>
                  <CgArrowsExchange className="h-[2rem] w-[2rem]" />
                </div>
              </div>

              {/* Main Part */}

              <div className="">{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
